---
- name: Setup for chroot environment
  setup:

- name: emerge-webrsync
  command: /usr/bin/emerge-webrsync
  # alphabetically the last category folder
  args:
    creates: /usr/portage/xfce-extra

- name: Install gentoolkit to have equery and be able to use package module
  command: emerge app-portage/gentoolkit
  args:
    creates: /usr/bin/equery

- name: Install sudo package
  package:
    name: app-admin/sudo
    state: present

- name: Set timezone
  copy:
    dest: /etc/timezone
    content: |
      {{ timezone }}
  register: timezone
  become: yes

- name: Configure timezone
  command: emerge --config sys-libs/timezone-data
  become: yes
  when: timezone is changed

- name: Configure locales
  lineinfile:
    path: /etc/locale.gen
    line: en_US.UTF-8 UTF-8
  register: locales
  become: yes

- name: Generate locales
  command: locale-gen
  become: yes
  when: locales is changed

- name: Set hostname
  copy:
    content: |
      hostname="{{ inventory_hostname_short }}"
    dest: /etc/conf.d/hostname
  become: yes

- name: Set use flag for grub
  copy:
    content: |
      sys-boot/grub device-mapper
    dest: /etc/portage/package.use/grub
  become: yes

- name: Install system packages
  package:
    name: "{{ item.name }}"
  with_items:
  - name: app-admin/logrotate
    creates: /mnt/gentoo/usr/bin/logrotate
  - name: app-admin/syslog-ng
    creates: /mnt/gentoo/usr/sbin/syslog-ng
  - name: sys-kernel/gentoo-sources
    creates: /mnt/gentoo/usr/src/linux/arch
  - name: sys-fs/mdadm
    creates: /mnt/gentoo/sbin/mdadm
  - name: sys-boot/grub
    creates: /mnt/gentoo/usr/sbin/grub-install
  - name: sys-fs/cryptsetup
    creates: /mnt/gentoo/sbin/cryptsetup

- name: Add syslog-ng to Default Run Configuration
  service:
    name: syslog-ng
    enabled: yes
    use: "{{ chroot_service_mgr }}"
    # https://github.com/ansible/ansible/issues/41830
    # use is default auto, but in chroot it recognize systemd instead
    # of openrc when host has systemd. Until the bug is fixed it must
    # be overwritten :( The pull request is working for me

- include: kernel.yml
- include: initramfs.yml
- include: network.yml
- include: grub.yml
