---
- name: Get luks uuid
  command: cryptsetup luksUUID /dev/disk/by-id/md-name-{{ inventory_hostname_short }}:crypt
  register: luks_uuid
  changed_when: False
  check_mode: no
  become: yes

- name: Assemble grub cmdline
  set_fact:
    grub_cmdline: >
      rd.neednet=1 rd.luks.uuid={{ luks_uuid.stdout }}
      rd.lvm.vg={{ inventory_hostname_short }}
      ip={% if use_dhcp %}dhcp{% else %}{{ ansible_default_ipv4.address }}::{{ ansible_default_ipv4.gateway }}:{{ ansible_default_ipv4.netmask }}:{{ inventory_hostname_short }}:{{ network_intf }}:off{% endif %}

- name: Configure grub
  lineinfile:
    path: /etc/default/grub
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
  with_items:
  - line: GRUB_ENABLE_CRYPTODISK=y
    regexp: ^GRUB_ENABLE_CRYPTODISK=
  - line: GRUB_CMDLINE_LINUX="{{ grub_cmdline | trim }}"
    regexp: ^GRUB_CMDLINE_LINUX=
  become: yes

- name: Install grub to boot drive
  command: grub-install /dev/sda
  become: yes

- name: Make grub config
  command: grub-mkconfig -o /boot/grub/grub.cfg
  become: yes
