---
- name: Ensure package.accept_keywords directory exist
  file:
    state: directory
    path: /etc/portage/package.accept_keywords
  become: yes

# dracut will be installed with dracut-crypt-ssh

- name: Create accept_keywords for dracut-crypt-ssh
  copy:
    content: |
      =sys-kernel/dracut-crypt-ssh-1.0.6-r1 ~amd64
    dest: /etc/portage/package.accept_keywords/dracut
  become: yes

- name: Install dracut-crypt-ssh
  package:
    name: sys-kernel/dracut-crypt-ssh
    state: present
  become: yes

- name: Set use flag for systemd
  copy:
    content: |
      sys-apps/systemd cryptsetup
    dest: /etc/portage/package.use/systemd
  become: yes
  when: use_systemd | bool

- name: Recompile systemd
  portage:
    package: sys-apps/systemd
    newuse: yes
    update: yes
  become: yes
  when: use_systemd | bool

- name: Check if openssh has bindist USE-flag
  command: emerge --info net-misc/openssh
  register: ssh_bindist
  changed_when: False
  check_mode: no

- name: Recompile openssh
  portage:
    package: net-misc/openssh
    newuse: yes
    update: yes
  when: not "-bindist" in ssh_bindist.stdout
  become: yes
  # Rebuild net-misc/openssh will also rebuild dev-libs/openssl
  # they are built with bindist use flag
  # dracut-dropbear wants to generate ecdsa keys
  # ecdsa has some patents on it, therefor it is disabled when bindist is enabled
  # https://forums.gentoo.org/viewtopic-t-901492-start-0.html

- name: Get linked version
  register: linked_kernel_version_src
  stat: 
    path: /usr/src/linux
  changed_when: false
  check_mode: no

- name: Set facts
  set_fact:
    linked_kernel_version: "{{ linked_kernel_version_src.stat.lnk_source | regex_replace('^.*linux-', '') }}"

- debug:
    var: linked_kernel_version

- name: Copy ssh host keys
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default('0600') }}"
  with_items: "{{ keys_to_copy }}"
  become: yes

- name: Configure dracut
  lineinfile:
    line: '{{ item.key }}="{{ item.value }}"'
    regexp: '^{{ item.key }}'
    path: /etc/dracut.conf.d/crypt-ssh.conf
  with_dict: "{{ dracut_crypt_ssh_conf }}"
  become: yes

- name: Create initramfs for {{ linked_kernel_version }}
  command: dracut --force --host-only --kver {{ linked_kernel_version }}
  become: yes
