---
- name: eselect profile list
  command: eselect profile list
  register: profile_list
  changed_when: False
  check_mode: no

- name: Create kernel default config
  command: make defconfig
  args:
    chdir: /usr/src/linux
    creates: /usr/src/linux/.config
  become: yes

- name: Copy kernel config fragment
  template:
    src: kernel-config.fragment.j2
    dest: /usr/src/kernel-config.fragment
  become: yes

- name: Apply code fragment
  command: scripts/kconfig/merge_config.sh -n .config ../kernel-config.fragment
  args:
    chdir: /usr/src/linux
  become: yes

- name: Run make oldconfig
  command: make oldconfig
  args:
    chdir: /usr/src/linux
  become: yes

- name: Make Kernel
  command: make -j{{ ansible_processor_vcpus+1 }}
  args:
    chdir: /usr/src/linux
  become: yes

- name: Make Module Install
  command: make modules_install
  args:
    chdir: /usr/src/linux
  become: yes

- name: Make Install
  command: make install
  args:
    chdir: /usr/src/linux
  become: yes
