---
- name: eselect profile list
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; eselect profile list'
  register: profile_list
  changed_when: False
  check_mode: no

- name: Copy kernel config
  copy:
    src: config-4.9.34-gentoo
    dest: /mnt/gentoo/usr/src/linux/.config
    force: no
  become: yes

- name: Copy kernel config fragment
  template:
    src: kernel-config.fragment.j2
    dest: /mnt/gentoo/usr/src/kernel-config.fragment

- name: Apply code fragment
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; cd /usr/src/linux; scripts/kconfig/merge_config.sh -n .config ../kernel-config.fragment'

- name: Run make oldconfig
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; cd /usr/src/linux; make oldconfig'
  become: yes

- name: Make Kernel
  command: chroot /mnt/gentoo/ bash -c 'source /etc/profile; cd /usr/src/linux; make -j{{ ansible_processor_vcpus+1 }}'
  become: yes

- name: Make Module Install
  command: chroot /mnt/gentoo/ bash -c 'source /etc/profile; cd /usr/src/linux; make modules_install'
  become: yes

- name: Make Install
  command: chroot /mnt/gentoo/ bash -c 'source /etc/profile; cd /usr/src/linux; make install'
  become: yes
