---
- name: emerge gentoo sources
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; emerge gentoo-sources'
  args:
    creates: /mnt/gentoo/usr/src/linux/arch
  become: yes

- name: eselect profile list
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; eselect profile list'
  register: profile_list
  changed_when: False
  check_mode: no

- debug:
    var: profile_list

- name: Copy kernel config
  copy:
    src: config-4.9.34-gentoo
    dest: /mnt/gentoo/usr/src/linux/.config
    force: no
  become: yes

- name: Run make oldconfig
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; cd /usr/src/linux; make oldconfig'
  become: yes

- name: Make Kernel
  command: chroot /mnt/gentoo/ bash -c 'source /etc/profile; cd /usr/src/linux; make -j{{ ansible_processor_vcpus+1 }}'
  become: yes

- name: Make Module Install
  command: chroot /mnt/gentoo/ bash -c 'source /etc/profile; cd /usr/src/linux; make modules_install'
  become: yes

- name: Make Install
  command: chroot /mnt/gentoo/ bash -c 'source /etc/profile; cd /usr/src/linux; make install'
  become: yes
