---
- include: prepare.yml
  tags:
  - prepare_chroot
- include: chroot.yml
- include: kernel.yml
- include: initramfs.yml
- include: network.yml
- include: grub.yml
- include: reboot.yml
  when: provider == 'hetzner'
