---
- name: Get predictable network interface name
  shell: udevadm test-builtin net_id /sys/class/net/{{ ansible_default_ipv4.interface }} | grep -E "ID_NET_NAME_(ONBOARD|SLOT|PATH)"
  register: network_interface
  become: yes
  check_mode: no
  changed_when: false

- name: Set name of network interface
  # predictable name for future use
  set_fact:
    network_intf: "{% if use_dhcp %}{{ ansible_default_ipv4.interface }}{% else %}{{ network_interface.stdout_lines.0.split('=')[1] }}{% endif %}"

- name: Create interface service
  file:
    src: net.lo
    dest: /etc/init.d/net.{{ network_intf }}
    state: link
  become: yes
  when: not (use_systemd | bool)

- name: Enable network service for {{ network_intf }}
  service:
    name: net.{{ network_intf }}
    enabled: yes
    use: "{{ chroot_service_mgr }}"
  when: not (use_systemd | bool)

- name: Enable systemd-resolved service
  service:
    name: systemd-resolved
    enabled: yes
    use: "{{ chroot_service_mgr }}"
  when: use_systemd | bool

- name: Enable sshd services
  service:
    name: "{{ item }}"
    enabled: yes
    use: "{{ chroot_service_mgr }}"
  with_items:
  - sshd

- name: Create network config
  copy:
    content: |
      config_{{ network_intf }}="noop {{ ansible_default_ipv4.address }}/{{ (ansible_default_ipv4.address+"/"+ansible_default_ipv4.netmask)|ipaddr('prefix') }}"
      routes_{{ network_intf }}="default via {{ ansible_default_ipv4.gateway }}"
    dest: /etc/conf.d/net
