---

- name: Enable chroot in sshd
  blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      Port 223
      Match LocalPort 223
        ChrootDirectory /mnt/gentoo
        X11Forwarding no
  notify: Restart sshd

- name: Use internal-sftp to make it work in chroot
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: ^Subsystem\s+sftp\s+.*
    line: Subsystem sftp internal-sftp
  notify: Restart sshd

- meta: flush_handlers

# Need this before the initramfs is created also vital to login to the decrypted system
- name: Set authorized key for user root copying it from current user
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
    path: /mnt/gentoo/root/.ssh/authorized_keys

- name: Copy DNS info
  copy:
    src: /etc/resolv.conf
    dest: /mnt/gentoo/etc/
    remote_src: yes

- name: Mount proc bind
  mount:
    path: /mnt/gentoo/proc
    fstype: proc
    src: /proc
    state: mounted

- name: Mount dev bind
  mount:
    path: /mnt/gentoo/dev
    fstype: none
    src: /dev
    opts: rbind
    state: mounted

- name: Mount sys bind
  mount:
    path: /mnt/gentoo/sys
    fstype: none
    src: /sys
    opts: rbind
    state: mounted
