---
- name: Install packages needed in rescue system
  package:
    name: "{{ item }}"
    state: present
  register: package_rescue
  retries: 10
  delay: 10
  until: package_rescue is success
  with_items:
  - cryptsetup-bin
  - dmsetup
  - lvm2
  - xz-utils
