---
- name: Fetch current raid info
  command: cat /proc/mdstat
  register: raid_stat
  changed_when: False

- name: Create raid 1 for boot
  vars:
    partition: 2
    jq: "[?contains(value, '{{ ansible_device_links.ids[storage_drives[0]][0] }}-part{{ partition }}') || contains(value, '{{ ansible_device_links.ids[storage_drives[1]][0] }}-part{{ partition }}')].key"
    parts: "{{ ansible_device_links.ids | dict2items | json_query(jq) | sort }}"
  command: mdadm --create /dev/md/boot --run --name={{ inventory_hostname_short }}:boot --metadata=1.2 --level=raid1 --raid-devices=2 /dev/{{ parts[0] }} /dev/{{ parts[1] }}
  when:
  - raid_stat.stdout.find(parts[0]) == -1
  - raid_stat.stdout.find(parts[1]) == -1

- name: Create raid 1 for crypt
  vars:
    partition: 3
    jq: "[?contains(value, '{{ ansible_device_links.ids[storage_drives[0]][0] }}-part{{ partition }}') || contains(value, '{{ ansible_device_links.ids[storage_drives[1]][0] }}-part{{ partition }}')].key"
    parts: "{{ ansible_device_links.ids | dict2items | json_query(jq) | sort }}"
  command: mdadm --create /dev/md/crypt --run --name={{ inventory_hostname_short }}:crypt --metadata=1.2 --level=raid1 --raid-devices=2 /dev/{{ parts[0] }} /dev/{{ parts[1] }}
  when:
  - raid_stat.stdout.find(parts[0]) == -1
  - raid_stat.stdout.find(parts[1]) == -1
