---
- name: Create filesystem for boot
  filesystem:
    fstype: ext4
    dev: /dev/md/boot
    opts: -L boot

- name: Create filesystem for root
  filesystem:
    fstype: ext4
    dev: /dev/mapper/{{ inventory_hostname_short }}-root
    opts: -L root

- name: Create filesystem for additional logical volumes
  filesystem:
    fstype: ext4
    dev: /dev/mapper/{{ inventory_hostname_short }}-{{ item.name }}
    opts: -L {{ item.name }} -m 0
  with_items: "{{ logical_volumes }}"
