---
- name: Select storage drives
  set_fact:
    storage_drives: "{{ ansible_devices | dict2items
    | selectattr('value.model') | selectattr('value.links.ids')
    | rejectattr('value.links.uuids') | rejectattr('value.holders')
    | map(attribute='key') | sort | list }}"

- name: Create new disc label and BIOS boot partition
  parted:
    device: "/dev/{{ item }}"
    label: gpt
    name: bios
    number: 1
    part_type: primary
    state: present
    flags:
    - bios_grub
    part_start: 2048s
    part_end: 10239s
    unit: s
  with_items: "{{ storage_drives }}"
- name: Create partition /boot
  parted:
    device: "/dev/{{ item }}"
    label: gpt
    name: boot
    number: 2
    part_type: primary
    state: present
    flags:
    - raid
    part_start: 10240s
    part_end: 1058815s
    unit: s
  with_items: "{{ storage_drives }}"
- name: Create partition for crypt
  parted:
    device: "/dev/{{ item }}"
    label: gpt
    name: crypt
    number: 3
    part_type: primary
    state: present
    flags:
    - raid
    part_start: 1058816s
    unit: s
  with_items: "{{ storage_drives }}"
- name: Setup after partitions are created
  setup:
